# Generated by Django 2.2.6 on 2020-01-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentadante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institucion')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo que desempeña')),
            ],
            options={
                'verbose_name': 'Cuentadante',
                'verbose_name_plural': 'Cuentadantes',
            },
        ),
        migrations.CreateModel(
            name='Sentencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('resolucion', models.BooleanField(blank=True, null=True, verbose_name='Resolucion')),
                ('camara', models.IntegerField(blank=True, null=True, verbose_name='Camara')),
                ('fecha_inicio_juicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Juicio')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolucion')),
                ('agente_auxiliar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Agente Auxiliar')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='PDF_sentencias/', verbose_name='Archivo')),
                ('cuentadantes', models.ManyToManyField(to='Sentencias.Cuentadante', verbose_name='Cuentadantes')),
            ],
            options={
                'verbose_name': 'sentencia',
                'verbose_name_plural': 'sentencias',
            },
        ),
    ]
