# Generated by Django 2.2.6 on 2020-01-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sentencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencia',
            name='agente_auxiliar',
        ),
        migrations.RemoveField(
            model_name='sentencia',
            name='cuentadantes',
        ),
        migrations.AddField(
            model_name='sentencia',
            name='instancia',
            field=models.IntegerField(default=None, verbose_name='Instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentencia',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institucion'),
        ),
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_reparo', models.CharField(max_length=50, verbose_name='Numero De Reparo')),
                ('cuentadantes', models.ManyToManyField(to='Sentencias.Cuentadante', verbose_name='Cuentadantes')),
                ('sentencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sentencia', to='Sentencias.Sentencia')),
            ],
            options={
                'verbose_name': 'Reparo',
                'verbose_name_plural': 'Reparos',
            },
        ),
    ]
