# Generated by Django 2.2.6 on 2020-01-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentencias', '0002_auto_20200110_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
