# Generated by Django 2.2.6 on 2020-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentencias', '0003_reparo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentadante',
            name='salario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salario'),
        ),
    ]
