# Generated by Django 2.2.6 on 2020-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentencias', '0007_auto_20200112_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparo',
            name='cuentadantes',
            field=models.ManyToManyField(related_name='Reparados', to='Sentencias.Cuentadante', verbose_name='Cuentadantes'),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='camara',
            field=models.IntegerField(blank=True, choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera'), (4, 'Cuarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Septima')], null=True, verbose_name='Camara'),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='instancia',
            field=models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda')], verbose_name='Instancia'),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='resolucion',
            field=models.BooleanField(blank=True, choices=[(True, 'Favorable'), (False, 'Desfavorable'), (None, 'Mixta')], null=True, verbose_name='Resolucion'),
        ),
    ]
